apiVersion: v1
kind: ConfigMap
metadata: # kpt-merge: istio-system/istio
  name: istio
  namespace: istio-system
  annotations:
    internal.kpt.dev/upstream-identifier: '|ConfigMap|istio-system|istio'
data:
  # Configuration file for the mesh networks to be used by the Split Horizon EDS.
  mesh: |-
    accessLogFile: /dev/stdout
    defaultConfig:
      discoveryAddress: istiod.istio-system.svc:15012
      proxyMetadata: {}
      tracing: {}
    enablePrometheusMerge: true
    rootNamespace: istio-system
    tcpKeepalive:
      interval: 5s
      probes: 3
      time: 10s
    trustDomain: cluster.local
