apiVersion: v1
kind: Namespace
metadata: # kpt-merge: /system
  labels:
    control-plane: controller-manager
  name: system
  annotations:
    internal.kpt.dev/upstream-identifier: '|Namespace|default|system'
---
apiVersion: apps/v1
kind: Deployment
metadata: # kpt-merge: /deployment
  name: deployment
  labels:
    control-plane: controller-manager
  annotations:
    internal.kpt.dev/upstream-identifier: 'apps|Deployment|default|deployment'
spec:
  selector:
    matchLabels:
      control-plane: controller-manager
  replicas: 1
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: manager
      labels:
        control-plane: controller-manager
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 999
      containers:
        - command:
            - /manager
          image: docker.io/kubeflownotebookswg/tensorboard-controller
          name: manager
          securityContext:
            allowPrivilegeEscalation: false
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8081
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            limits:
              cpu: 500m
              memory: 128Mi
            requests:
              cpu: 10m
              memory: 64Mi
      serviceAccountName: controller-manager
      terminationGracePeriodSeconds: 10
