apiVersion: v1
kind: ConfigMap
metadata: # kpt-merge: knative-serving/config-istio
  name: config-istio
  namespace: knative-serving
  annotations:
    internal.kpt.dev/upstream-identifier: '|ConfigMap|knative-serving|config-istio'
data:
  gateway.kubeflow.kubeflow-gateway: istio-ingressgateway.istio-system.svc.cluster.local
---
apiVersion: v1
kind: ConfigMap
metadata: # kpt-merge: knative-serving/config-deployment
  name: config-deployment
  namespace: knative-serving
  annotations:
    internal.kpt.dev/upstream-identifier: '|ConfigMap|knative-serving|config-deployment'
data:
  progressDeadline: 600s
