apiVersion: v1
kind: Namespace
metadata: # kpt-merge: /knative-serving
  name: knative-serving
  labels:
    istio-injection: enabled
  annotations:
    internal.kpt.dev/upstream-identifier: '|Namespace|default|knative-serving'
