apiVersion: v1
kind: Service
metadata: # kpt-merge: istio-system/knative-local-gateway
  name: knative-local-gateway
  namespace: istio-system
  labels:
    experimental.istio.io/disable-gateway-port-translation: "true"
  annotations:
    internal.kpt.dev/upstream-identifier: '|Service|istio-system|knative-local-gateway'
