apiVersion: v1
data:
  $patch: replace # We do not need some of the original fields.
  admin: pablo.ordoricaw@gmail.com # kpt-set: ${email}
  gcp-sa: kubeflow-user@columbia-ms-courses-home.iam.gserviceaccount.com # kpt-set: ${name}-user@${gcloud.core.project}.iam.gserviceaccount.com
kind: ConfigMap
metadata:
  name: config
