apiVersion: core.cnrm.cloud.google.com/v1beta1
kind: ConfigConnector
metadata:
  name: configconnector.core.cnrm.cloud.google.com
spec:
  mode: cluster
  googleServiceAccount: "kubeflow-chef-cnrm-system@columbia-ms-courses-home.iam.gserviceaccount.com" # kpt-set: ${name}-cnrm-system@${gcloud.core.project}.iam.gserviceaccount.com
