apiVersion: v1
kind: Namespace
metadata: # kpt-merge: /istio-system
  name: istio-system
  labels:
    istio-operator-managed: Reconcile
    istio-injection: disabled
  annotations:
    internal.kpt.dev/upstream-identifier: '|Namespace|default|istio-system'
