apiVersion: v1
kind: Service
metadata: # kpt-merge: /service
  labels:
    app: notebook-controller
    kustomize.component: notebook-controller
  name: service
  annotations:
    internal.kpt.dev/upstream-identifier: '|Service|default|service'
spec:
  ports:
  - port: 443
  selector:
    app: notebook-controller
    kustomize.component: notebook-controller
