apiVersion: v1
kind: Namespace
metadata: # kpt-merge: /system
  labels:
    control-plane: controller-manager
  name: system
  annotations:
    internal.kpt.dev/upstream-identifier: '|Namespace|default|system'
---
apiVersion: apps/v1
kind: Deployment
metadata: # kpt-merge: /deployment
  name: deployment
  annotations:
    internal.kpt.dev/upstream-identifier: 'apps|Deployment|default|deployment'
spec:
  replicas: 1
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      containers:
      - command:
        - /manager
        - "-userid-header"
        - $(USERID_HEADER)
        - "-userid-prefix"
        - $(USERID_PREFIX)
        - "-workload-identity"
        - $(WORKLOAD_IDENTITY)
        envFrom:
        - configMapRef:
            name: config
        image: docker.io/kubeflownotebookswg/profile-controller
        imagePullPolicy: IfNotPresent
        name: manager
        livenessProbe:
          httpGet:
            path: /healthz
            port: 9876
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /readyz
            port: 9876
          initialDelaySeconds: 5
          periodSeconds: 10
        ports:
        - containerPort: 9876
      serviceAccountName: controller-manager
