apiVersion: v1
kind: Service
metadata: # kpt-merge: /service
  name: service
  annotations:
    internal.kpt.dev/upstream-identifier: '|Service|default|service'
spec:
  ports:
  - name: https-webhook
    port: 443
    targetPort: https-webhook
