apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata: # kpt-merge: kubeflow/leader-election
  name: leader-election
  namespace: kubeflow
  annotations:
    internal.kpt.dev/upstream-identifier: 'rbac.authorization.k8s.io|Role|kubeflow|leader-election'
rules:
  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    verbs:
      - "*"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata: # kpt-merge: kubeflow/leader-election
  name: leader-election
  namespace: kubeflow
  annotations:
    internal.kpt.dev/upstream-identifier: 'rbac.authorization.k8s.io|RoleBinding|kubeflow|leader-election'
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: leader-election
subjects:
  - kind: ServiceAccount
    name: katib-controller
    namespace: kubeflow
