apiVersion: v1
kind: Service
metadata: # kpt-merge: system/controller-manager-metrics-service
  annotations:
    prometheus.io/port: "8443"
    prometheus.io/scheme: https
    prometheus.io/scrape: "true"
    internal.kpt.dev/upstream-identifier: '|Service|system|controller-manager-metrics-service'
  labels:
    control-plane: controller-manager
  name: controller-manager-metrics-service
  namespace: system
spec:
  ports:
  - name: https
    port: 8443
    targetPort: https
  selector:
    control-plane: controller-manager
