apiVersion: v1
kind: Service
metadata: # kpt-merge: system/webhook-service
  name: webhook-service
  namespace: system
  annotations:
    internal.kpt.dev/upstream-identifier: '|Service|system|webhook-service'
spec:
  ports:
    - port: 443
      targetPort: 9443
  selector:
    control-plane: controller-manager
