apiVersion: v1
kind: ServiceAccount
metadata: # kpt-merge: /training-operator
  labels:
    app: training-operator
  name: training-operator
  annotations:
    internal.kpt.dev/upstream-identifier: '|ServiceAccount|default|training-operator'
