apiVersion: kubeflow.org/v1alpha1
kind: Notebook
metadata: # kpt-merge: /notebook-sample-v1alpha1
  name: notebook-sample-v1alpha1
  annotations:
    internal.kpt.dev/upstream-identifier: 'kubeflow.org|Notebook|default|notebook-sample-v1alpha1'
spec:
  template:
    spec:
      containers:
        - name: notebook-sample-v1
          image: kubeflownotebookswg/jupyter:latest
