apiVersion: v1
kind: ServiceAccount
metadata:
  name: ml-pipeline-ui
  annotations:
    iam.gke.io/gcp-service-account: kubeflow-user@columbia-ms-courses-home.iam.gserviceaccount.com # kpt-set: ${name}-user@${gcloud.core.project}.iam.gserviceaccount.com
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ml-pipeline-visualizationserver
  annotations:
    iam.gke.io/gcp-service-account: kubeflow-user@columbia-ms-courses-home.iam.gserviceaccount.com # kpt-set: ${name}-user@${gcloud.core.project}.iam.gserviceaccount.com
