apiVersion: v1
kind: Service
metadata: # kpt-merge: /training-operator
  annotations:
    prometheus.io/path: /metrics
    prometheus.io/scrape: "true"
    prometheus.io/port: "8080"
    internal.kpt.dev/upstream-identifier: '|Service|default|training-operator'
  labels:
    app: training-operator
  name: training-operator
spec:
  ports:
  - name: monitoring-port
    port: 8080
    targetPort: 8080
  selector:
    control-plane: kubeflow-training-operator
  type: ClusterIP
