apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicyMember
metadata:
  name: kubeflow-user-workload-identity-user-ml-pipeline-ui # kpt-set: ${name}-user-workload-identity-user-ml-pipeline-ui
spec:
  member: serviceAccount:columbia-ms-courses-home.svc.id.goog[kubeflow/ml-pipeline-ui] # kpt-set: serviceAccount:${gcloud.core.project}.svc.id.goog[kubeflow/ml-pipeline-ui]
  role: roles/iam.workloadIdentityUser
  resourceRef:
    apiVersion: iam.cnrm.cloud.google.com/v1beta1
    kind: IAMServiceAccount
    name: kubeflow-user # kpt-set: ${name}-user
---
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicyMember
metadata:
  name: kubeflow-user-workload-identity-user-ml-pipeline-visualizationserver # kpt-set: ${name}-user-workload-identity-user-ml-pipeline-visualizationserver
spec:
  member: serviceAccount:columbia-ms-courses-home.svc.id.goog[kubeflow/ml-pipeline-visualizationserver] # kpt-set: serviceAccount:${gcloud.core.project}.svc.id.goog[kubeflow/ml-pipeline-visualizationserver]
  role: roles/iam.workloadIdentityUser
  resourceRef:
    apiVersion: iam.cnrm.cloud.google.com/v1beta1
    kind: IAMServiceAccount
    name: kubeflow-user # kpt-set: ${name}-user
---
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicyMember
metadata:
  name: kubeflow-user-workload-identity-user-pipeline-runner # kpt-set: ${name}-user-workload-identity-user-pipeline-runner
spec:
  member: serviceAccount:columbia-ms-courses-home.svc.id.goog[kubeflow/pipeline-runner] # kpt-set: serviceAccount:${gcloud.core.project}.svc.id.goog[kubeflow/pipeline-runner]
  role: roles/iam.workloadIdentityUser
  resourceRef:
    apiVersion: iam.cnrm.cloud.google.com/v1beta1
    kind: IAMServiceAccount
    name: kubeflow-user # kpt-set: ${name}-user
