apiVersion: v1
kind: Service
metadata: # kpt-merge: kubeflow/katib-db-manager
  name: katib-db-manager
  namespace: kubeflow
  labels:
    katib.kubeflow.org/component: db-manager
  annotations:
    internal.kpt.dev/upstream-identifier: '|Service|kubeflow|katib-db-manager'
spec:
  type: ClusterIP
  ports:
    - port: 6789
      protocol: TCP
      name: api
  selector:
    katib.kubeflow.org/component: db-manager
