apiVersion: v1
kind: PersistentVolumeClaim
metadata: # kpt-merge: kubeflow/katib-mysql
  name: katib-mysql
  namespace: kubeflow
  annotations:
    internal.kpt.dev/upstream-identifier: '|PersistentVolumeClaim|kubeflow|katib-mysql'
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
