apiVersion: v1
kind: Service
metadata: # kpt-merge: system/controller-manager-metrics-service
  labels:
    control-plane: controller-manager
  name: controller-manager-metrics-service
  namespace: system
  annotations:
    internal.kpt.dev/upstream-identifier: '|Service|system|controller-manager-metrics-service'
spec:
  ports:
    - name: https
      port: 8443
      protocol: TCP
      targetPort: https
  selector:
    control-plane: controller-manager
