apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata: # kpt-merge: /metrics-reader
  name: metrics-reader
  annotations:
    internal.kpt.dev/upstream-identifier: 'rbac.authorization.k8s.io|ClusterRole|default|metrics-reader'
rules:
- nonResourceURLs:
  - "/metrics"
  verbs:
  - get
