# permissions for end users to view profiles.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata: # kpt-merge: /profile-viewer-role
  name: profile-viewer-role
  annotations:
    internal.kpt.dev/upstream-identifier: 'rbac.authorization.k8s.io|ClusterRole|default|profile-viewer-role'
rules:
- apiGroups:
  - kubeflow.org
  resources:
  - profiles
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - kubeflow.org
  resources:
  - profiles/status
  verbs:
  - get
