apiVersion: v1
kind: Service
metadata: # kpt-merge: kubeflow/katib-ui
  name: katib-ui
  namespace: kubeflow
  labels:
    katib.kubeflow.org/component: ui
  annotations:
    internal.kpt.dev/upstream-identifier: '|Service|kubeflow|katib-ui'
spec:
  type: ClusterIP
  ports:
    - port: 80
      protocol: TCP
      name: ui
      targetPort: 8080
  selector:
    katib.kubeflow.org/component: ui
