apiVersion: apps/v1
kind: Deployment
metadata: # kpt-merge: kserve/kserve-models-web-app
  name: kserve-models-web-app
  namespace: kserve
  annotations:
    internal.kpt.dev/upstream-identifier: 'apps|Deployment|kserve|kserve-models-web-app'
spec:
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "true"
