# Prometheus Monitor Service (Metrics)
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata: # kpt-merge: system/controller-manager-metrics-monitor
  labels:
    control-plane: controller-manager
  name: controller-manager-metrics-monitor
  namespace: system
  annotations:
    internal.kpt.dev/upstream-identifier: 'monitoring.coreos.com|ServiceMonitor|system|controller-manager-metrics-monitor'
spec:
  endpoints:
    - path: /metrics
      port: https
      scheme: https
      bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
      tlsConfig:
        insecureSkipVerify: true
  selector:
    matchLabels:
      control-plane: controller-manager
