apiVersion: cert-manager.io/v1
kind: Certificate
metadata: # kpt-merge: /cert
  name: cert
  annotations:
    internal.kpt.dev/upstream-identifier: 'cert-manager.io|Certificate|default|cert'
spec:
  isCA: true
  commonName: $(podDefaultsServiceName).$(podDefaultsNamespace).svc
  dnsNames:
  - $(podDefaultsServiceName).$(podDefaultsNamespace).svc
  - $(podDefaultsServiceName).$(podDefaultsNamespace).svc.cluster.local
  issuerRef:
    kind: Issuer
    name: selfsigned-issuer
  secretName: webhook-certs
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata: # kpt-merge: /selfsigned-issuer
  name: selfsigned-issuer
  annotations:
    internal.kpt.dev/upstream-identifier: 'cert-manager.io|Issuer|default|selfsigned-issuer'
spec:
  selfSigned: {}
