apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata: # kpt-merge: /mutating-webhook-configuration
  name: mutating-webhook-configuration
  annotations:
    cert-manager.io/inject-ca-from: $(podDefaultsNamespace)/$(podDefaultsCertName)
    internal.kpt.dev/upstream-identifier: 'admissionregistration.k8s.io|MutatingWebhookConfiguration|default|mutating-webhook-configuration'
